# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MichaChatGPTBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js version
        uses:  actions/setup-node@v3.6.0
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: 'Create env file'
        run: |
          touch .env
          echo OPEN_API_KEY=${{ secrets.OPEN_API_KEY }} >> .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          cat .env

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: Azure/webapps-deploy@v2.2.5
        with:
          app-name: 'MichaChatGPTBot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D0B8405DB6D741E285F6DC5F07D6FCCF }}
          package: .
